# This is a basic workflow that is manually triggered

name: Daily Changes Tag

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  create-tag:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Generate shell information
      id: shellinfo
      # --abbrev=0 turns "Tagname-NCommitsSince-Hash" into "Tagname"
      # If there are no commits since the last commit, the two are both just "Tagname"
      run: |
        echo "::set-output name=date::$(date +'%a-%b-%m-%d')"
        echo "::set-output name=tag::$(git describe --tags)"           
        echo "::set-output name=tagabbrev::$(git describe --tags --abbrev=0)"
    - name: Create tag
      uses: actions/github-script@v7
      env:
        DATE: '${{steps.shellinfo.outputs.date}}'
        TAG:  '${{steps.shellinfo.outputs.tag}}'
        TAGABBREV: '${{steps.shellinfo.outputs.tagabbrev}}'
      with:
        script: |
          // Extract environment variables
          const { DATE, TAG, TAGABBREV } = process.env;

          if (TAG === TAGABBREV) {
            console.log("No updates since last tag! No need for new one.");
            return;
          }

          let repo = context.repo;
          github.rest.git.createRef({
            owner: repo.owner,
            repo: repo.repo,
            ref: `refs/tags/${DATE.trim()}`,
            sha: context.sha
          });
