name: Daily Changes Tag

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Generate tag if necessary
      run: |
        # Configure current user just in case
        
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        export TAG="$(git describe --tags)"
        export ABBREV="$(git describe --tags --abbrev=0)"
        echo -e "TAG: $TAG\nABBREV: $ABBREV"
        
        if [ "$TAG" = "$ABBREV" ]; then
          echo "FOUND DIFFERENCES SINCE LAST TAG. GENERATING NEW."
          git tag "$(date +'%a-%b-%m-%d')"
          git push --all
        else
          echo "-- No differences since last tag. --" 
        fi;
