name: Daily Changes Tag

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Generate tag if necessary
      run: |
        # Configure current user just in case
        git remote set-url origin https://${{ github.token }}@github.com/Proxxa/nvimconfig

        export TAG="$(git describe --tags)"
        export ABBREV="$(git describe --tags --abbrev=0)"
        echo -e "TAG:\t$TAG\nABBREV:\t$ABBREV"
        
        if [ "$TAG" != "$ABBREV" ]; then
          echo "FOUND DIFFERENCES SINCE LAST TAG. GENERATING NEW."
          git tag "$(date +'%a-%b-%m-%d')"
          git push --tags
        else
          echo "-- No differences since last tag. --" 
        fi;
