name: Daily Changes Tag

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Generate shell information
      id: shellinfo
      # --abbrev=0 turns "Tagname-NCommitsSince-Hash" into "Tagname"
      # If there are no commits since the last commit, the two are both just "Tagname"
      run: |
        echo "::set-output name=date::$(date +'%a-%b-%m-%d')"
        echo "::set-output name=tag::$(git describe --tags)"           
        echo "::set-output name=tagabbrev::$(git describe --tags --abbrev=0)"
    - name: Create tag
      uses: actions/github-script@v7
      env:
        DATE: '${{steps.shellinfo.outputs.date}}'
        TAG:  '${{steps.shellinfo.outputs.tag}}'
        TAGABBREV: '${{steps.shellinfo.outputs.tagabbrev}}'
      with:
        script: |
          // Extract environment variables
          const { DATE, TAG, TAGABBREV } = process.env;

          if (TAG === TAGABBREV) {
            console.log("No updates since last tag! No need for new one.");
            return;
          }

          let repo = context.repo;
          github.rest.git.createRef({
            owner: repo.owner,
            repo: repo.repo,
            ref: `refs/tags/${DATE.trim()}`,
            sha: context.sha
          });
